test_7/config/routes.rb
Test7::Application.routes.draw do
  get "users/new"
  match '/signup',  to: 'users#new', via: 'get'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  put    '/users/:id(.:format)', to: 'account#show'
  get 'users/:id/edit' => "users#edit",  :as => 'edit'
  post 'users/:id' => "users#update", :as => 'update_user'
end

test_7/app/models/user.rb
class User < ActiveRecord::Base
  require 'bcrypt'
  before_create :create_remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format:   { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, length: {minimum: 6}

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

test_7/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include SessionsHelper
  protect_from_forgery with: :exception
end

test_7/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to signin_path
  end
end

test_7/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
  end

  def create
    @user = User.new(user_params)
    if @user.save
        sign_in @user
        redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end



  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      render 'success'
    else
      render 'failure'
    end
  end


  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

test_7/app/helpers/application_helper.rb
module ApplicationHelper
end

test_7/app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

test_7/app/helpers/users_helper.rb
module UsersHelper
end

test_7/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test7</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

test_7/app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= form_for @user, url: update_user_path do |f| %>    

  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :email %>
  <%= f.email_field :email %>
  
  <%= f.label :password %>
  <%= f.password_field :password%>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation%>


  <%= f.submit 'Save Settings' %>
  <%end%>

test_7/app/views/users/failure.html.erb
<h1>Failure</h1>

<%= link_to 'Go back to your account', user_path %> </h3>

test_7/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

test_7/app/views/users/show.html.erb
<h1>Your Account Info:</h1>

<h2> Your Name: <%= @user.name %> </h2>
<h2> Your Email: <%= @user.email %></h3>
<%= link_to 'Change your Password', edit_user_path %> </h3>

<%= link_to "Sign out", signout_path, method: "delete" %>

test_7/app/views/users/success.html.erb
<h1>Success</h1>

<%= link_to 'Go back to your account', user_path %> </h3>

test_7/app/views/users/update.html.erb
<%- if @user.changed? && @user.save %>
  <h1> Password updated! </h1>
<%- else %>
  <h1> Not saved properly, please try again. </h1>
<%- end %>

<%= link_to 'Go back to your account', user_path %> </h3>